################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################

find_program (
    GSL_BIN
    gsl
)

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(
    GSL
    REQUIRED_VARS GSL_BIN
)
mark_as_advanced(
    GSL_FOUND
)

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
